name: Publish
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: pass environment
        uses: appleboy/ssh-action@master
        with:
          host: host-3.sitedistrict.com
          username: aamzes
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd
            ls -la
        id: wait-for-build
      - name: Move plugin directory
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: cd /home/aamzes/sites/cicd.sitedistrict.com/www/wp-content/plugins/ci-cd-sitedistrict/
      - name: Update from repository
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: git pull
